#!/usr/bin/env bash
#Creating a script that uses a nested loop
hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -It 60 ]
    do
	echo "$minutes"
	((minutes++)
    done
    ((hour++))
done
